### PR TITLE
Updated acknowledgement text

### PR DESCRIPTION
**Pull request by parlundin**
@ewels @b97pla

### CODE REVIEW

**Comment by ewels** [comment]
I guess NGI Pipeline also knows which node is running the analysis? But may be more tricky to add this info here I guess. Happy to merge as is if so. @b97pla?

**Comment by b97pla** [comment]
This file is just static and is being picked up by TACA upon staging, so it's a bit misplaced in this repo actually.. Would make more sense to deploy it with the environment or with TACA and then it would be easier to adapt values dynamically. But lacking that, I'm happy with merging this.

**Comment by parlundin** [comment]
One option is of course to have 2 files, one for uppsala and one for sthlm.
ACKNOWLEDGEMENTS_STHLM.txt and ACKNOWLEDGEMENTS_UA.txt Since we any how use different yml files when staging.

**Comment by ewels** [comment]
Two files seems nice and simple, I like it! Maybe just `-S` and `-U` instead of STHLM and U though?

**Pull request merged**
