### PR TITLE
Introduce a mascot

### PR DESCRIPTION
**Pull request by robinandeer**
Hi @mariogiov!

A going away present :cry:

gh-splash

I don't know exactly what a narwhal has to do with NGS analysis but they are indeed extraordinary creatures with unique adaptations. I read somewhere that they average dive times around 25 minutes and to depths of up to a mile! And of course they thrive in the nordic regions ^^

I know you had an awesome logo in the works so take this one or leave it :smiley:
I'm also by no means adverse to any critique or feedback!

### CODE REVIEW

**Comment by guillermo-carrasco** [comment]
wow, never heard of this animal before!

**Comment by mariogiov** [comment]
Ha Robin! This is amazing! I love narwhals! I used to work with a woman who studied these guys.
The logo I made was mostly just so I could write "Your Mom" on a new thing and I think this is much better.

The biologist in me wonders if you can move his eyes back around his horn? Technically that thing is a big long tooth and so comes out his mouth. But if that's tricky, no worries and I think it's great as it is too! It might look weird in cartoon form anyway.

**Comment by robinandeer** [comment]
I'm happy you like it - thank you Mario!

You're right though - now it's some kind of a unicorn/narwhal mutant :laughing:

I'll see what I can do but I'm not sure what it's going to look like, especially with the mustache.

**Comment by mariogiov** [comment]
Well unicorns are great too and at the moment he reminds me a bit of the Walrus from Alice and Wonderland so I think it might be great just the way it is. See what you think! I'll defer to your logo-making wisdom.

A perfect going-away present! I felt bad leaving the ngi_pipeline without a mascot.

**Comment by robinandeer** [comment]
:grin:

... and I think we'll have to just say it looks perfect as is... XD

gh-splash

**Comment by mariogiov** [comment]
Fantastic! I'm thinking maybe we can make up some Swedish sounding name for him like "Vymalm" so that his real name is "Y.Mom," my favorite moniker. Anyway I merge and adopt!

**Comment by robinandeer** [comment]
Hehehe, that made me laugh! Vymalm...

Yay! Another genomics pipeline I've made a logo for!

**Comment by johandahlberg** [comment]
Love this! :smile:

**Pull request merged**
