### PR TITLE
LOG.warn -> LOG.warning

### PR DESCRIPTION
**Pull request by MatildaAslin**
This PR changes all of occurrences of `LOG.warn` to `LOG.warning`. `warn` is not a function of `logging` and would therefore make the pipeline crash.

### CODE REVIEW

**Comment by b97pla** [comment]
@MatildaAslin are you sure about this, that sounds very strange (it shouldn't just start breaking now).. has some version of the interpreter or logging module changed?

**Comment by senthil10** [comment]
@b97pla I had the same question in my mind and just checked the `logging` module versions in current and previous deployment. They both were '0.5.1.2'

**Comment by MatildaAslin** [comment]
I'm pretty sure. I think the problem is that we have no tests for these scenarios and that they don't trigger very often. I got this error when trying to organize a flowcell with two projects, one present i Charon and one that is not in Charon. Even though I used the `--restrict-to-projects` flag the pipeline crashed since the not-in-charon-project was parsed first.  
```
Traceback (most recent call last):
  File "/lupus/ngi/production/v1.13/sw/anaconda/envs/NGI/bin/ngi_pipeline_start.py", line 473, in <module>
    quiet=args.quiet)
  File "/lupus/ngi/production/v1.13/sw/anaconda/envs/NGI/lib/python2.7/site-packages/ngi_pipeline/utils/classes.py", line 31, in __call__
    return self.f(**kwargs)
  File "/lupus/ngi/production/v1.13/sw/anaconda/envs/NGI/lib/python2.7/site-packages/ngi_pipeline/conductor/flowcell.py", line 151, in organize_projects_from_flowcell
    quiet=quiet)
  File "/lupus/ngi/production/v1.13/sw/anaconda/envs/NGI/lib/python2.7/site-packages/ngi_pipeline/utils/classes.py", line 31, in __call__
    return self.f(**kwargs)
  File "/lupus/ngi/production/v1.13/sw/anaconda/envs/NGI/lib/python2.7/site-packages/ngi_pipeline/conductor/flowcell.py", line 280, in setup_analysis_directory_structure
    LOG.warn('Could not retrieve project id from Charon (record missing?). '
AttributeError: 'LoggerAdapter' object has no attribute 'warn'
```

I wanted to write a test for `setup_analysis_directory_structure`, but I think the function has to be refactored before tests can be written. And that's kind of a big project.

**Comment by senthil10** [comment]
Yes, and also like the _error_ message states `logging.LoggerAdapter` don't have `warn` attribute

```
>>> dir(logging.LoggerAdapter)
['__class__', '__delattr__', '__dict__', '__doc__', '__format__',
'__getattribute__', '__hash__', '__init__', '__module__', '__new__',
'__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__',
'__str__', '__subclasshook__', '__weakref__', 'critical', 'debug',
'error', 'exception', 'info', 'isEnabledFor',
'log', 'process', 'warning']
```

**Comment by b97pla** [comment]
ah, that does look like the culprit

**Comment by MatildaAslin** [comment]
@b97pla Should we restore that change instead?

**Comment by b97pla** [comment]
not restore it but fix so that it returns the correct instance.. do you want to have a look at that?

**Comment by MatildaAslin** [comment]
Yes, can give it a try. :+1:

**Comment by b97pla** [comment]
ok, so to summarize: 

The `Logger` class implements both the `warn` and the `warning` methods. The `LoggerAdapter` is supposed to just forward calls transparently to the underlying `Logger` instance but it doesn't do that for the calls to `warn`.

The most robust and straightforward fix seems to me to replace all calls to `warn` with `warning` instead (which is what this PR actually does). I think it just needs to include some calls which are not to instances obtained from `minimal_logger` but let's include those for consistency.

**Comment by senthil10** [comment]
Great @b97pla and @MatildaAslin 👍 Pontus please go ahead and merge when you think it is ready, I will include then I will include that commit version in `irma_provision`

**Comment by MatildaAslin** [comment]
All occurrences of `.warn(` are already changed, @b97pla . Feel free to merge.

**Pull request merged**
