### PR TITLE
FRESH --> STALE upon FC organisation

### PR DESCRIPTION
**Pull request by vezzi**
Until now a sample was transitioning from FRESH to STALE when starting BP, but then this affected the status of samples that do not undergo BP (non WHG).
I changed the logic in such  a way that now samples become STALE when we organise them.

In Stockholm case if new data is produced ACHERON will set the status of a STALE sample to FRESH again and upon organisation the sample will become again STALE. 

This is the first of three PR for GRUS-delivery

### CODE REVIEW

**Comment by vezzi** [comment]
just realise that the TACA PR has been already merged.. so this is the first of two PRs....

**Comment by b97pla** [comment]
looks ok to me

**Comment by vezzi** [comment]
this is stable. @sylvinite @Galithil can you double check and merge if everything is fine? thanks

**Comment by sylvinite** [comment]
Looks good to me.

**Comment by vezzi** [comment]
@sylvinite you can proceed to merge then

**Pull request merged**
