### PR TITLE
WIP: Generic flowcell parsing + ~bugfix + modify libprep searching

### PR DESCRIPTION
**Pull request by mariogiov**

### CODE REVIEW

**Comment by mariogiov** [comment]
At the moment this means we'll skip samples for which we cannot determine the libprep (instead of making them `Unknown`) but until we implement the ngi_pipeline I think this is desirable.

**Comment by mariogiov** [comment]
Oh but now that I think of it I need to fix the Uppsala samplesheet parsing before we should merge this. Hold off.

**Comment by vezzi** [comment]
tell us when it is time to review the code :-D

**Comment by mariogiov** [comment]
Merged into another PR

**Pull request closed without merging**
